import type { DocumentCategory } from '@/types'

export const documentCategories: DocumentCategory[] = [
  {
    title: 'Core Export Documents',
    description:
      'Required for every international shipment regardless of destination',
    items: [
      {
        name: 'Commercial Invoice',
        filename: 'commercial-invoice.html',
        tag: 'Universal',
        tagColor: 'bg-blue-100 text-blue-800',
        icon: 'FileText',
        desc: 'Standard commercial invoice for international shipments',
        countries: 'All countries',
      },
      {
        name: 'Packing List',
        filename: 'packing-list.html',
        tag: 'Universal',
        tagColor: 'bg-blue-100 text-blue-800',
        icon: 'Package',
        desc: 'Detailed packing list for cargo documentation',
        countries: 'All countries',
      },
      {
        name: 'Proforma Invoice',
        filename: 'proforma-invoice.html',
        tag: 'Universal',
        tagColor: 'bg-blue-100 text-blue-800',
        icon: 'FileText',
        desc: 'Proforma invoice for quote and LC purposes',
        countries: 'All countries',
      },
    ],
  },
  {
    title: 'Freight & Transport Documents',
    description:
      'Issued per mode of transport - sea or air',
    items: [
      {
        name: 'Bill of Lading (Sea)',
        filename: 'bill-of-lading.html',
        tag: 'Sea / Air Freight',
        tagColor: 'bg-indigo-100 text-indigo-800',
        icon: 'Ship',
        desc: 'Ocean Bill of Lading for sea freight shipments',
        countries: 'Sea freight shipments',
      },
      {
        name: 'Air Waybill (AWB)',
        filename: 'air-waybill.html',
        tag: 'Sea / Air Freight',
        tagColor: 'bg-indigo-100 text-indigo-800',
        icon: 'Plane',
        desc: 'Air Waybill for air freight shipments',
        countries: 'Air freight shipments',
      },
      {
        name: 'Marine Insurance Certificate',
        filename: 'insurance-certificate.html',
        tag: 'Sea / Air Freight',
        tagColor: 'bg-indigo-100 text-indigo-800',
        icon: 'Shield',
        desc: 'Marine insurance certificate for cargo protection',
        countries: 'All countries',
      },
      {
        name: 'Fumigation Certificate (ISPM-15)',
        filename: 'fumigation-certificate.html',
        tag: 'Sea / Air Freight',
        tagColor: 'bg-indigo-100 text-indigo-800',
        icon: 'FlaskConical',
        desc: 'ISPM-15 fumigation certificate for wooden packaging',
        countries: 'All countries (wood packaging)',
      },
      {
        name: 'Dangerous Goods Declaration',
        filename: 'dangerous-goods-declaration.html',
        tag: 'Sea / Air Freight',
        tagColor: 'bg-indigo-100 text-indigo-800',
        icon: 'AlertTriangle',
        desc: 'Dangerous Goods Declaration for hazmat shipments',
        countries: 'All countries (DG shipments)',
      },
    ],
  },
  {
    title: 'Product Certificates & Country-Specific Compliance',
    description:
      'Required by importing countries for specific product types',
    items: [
      {
        name: 'Certificate of Origin Checklist',
        filename: 'certificate-of-origin-checklist.html',
        tag: 'Universal',
        tagColor: 'bg-blue-100 text-blue-800',
        icon: 'ScrollText',
        desc: 'Non-preferential COO checklist for general exports',
        countries: 'All countries',
      },
      {
        name: 'Health & Sanitary Certificate',
        filename: 'health-sanitary-certificate.html',
        tag: 'Food & Agri',
        tagColor: 'bg-emerald-100 text-emerald-800',
        icon: 'Apple',
        desc: 'Health and sanitary certificate for food products',
        countries: 'All countries (food items)',
      },
      {
        name: 'Pre-Shipment Inspection Certificate',
        filename: 'psi-certificate.html',
        tag: 'Universal',
        tagColor: 'bg-blue-100 text-blue-800',
        icon: 'SearchCheck',
        desc: 'Pre-shipment inspection certificate for quality assurance',
        countries: 'All countries',
      },
      {
        name: 'Halal Certificate Application',
        filename: 'halal-certificate-application.html',
        tag: 'Halal (OIC)',
        tagColor: 'bg-green-100 text-green-800',
        icon: 'Moon',
        desc: 'Halal certificate application form for OIC countries',
        countries: 'OIC / Islamic countries',
      },
      {
        name: 'US FDA Prior Notice Checklist',
        filename: 'fda-prior-notice-checklist.html',
        tag: 'USA',
        tagColor: 'bg-red-100 text-red-800',
        icon: 'ClipboardCheck',
        desc: 'US FDA prior notice checklist for food imports to USA',
        countries: 'USA (food items)',
      },
      {
        name: 'Safety Data Sheet (SDS / MSDS)',
        filename: 'safety-data-sheet.html',
        tag: 'Hazmat / DG',
        tagColor: 'bg-orange-100 text-orange-800',
        icon: 'TriangleAlert',
        desc: 'Safety data sheet for chemical/hazardous materials',
        countries: 'All countries (chemicals)',
      },
    ],
  },
  {
    title: 'Preferential Origin Certificates (FTA / Trade Agreements)',
    description:
      'Claim reduced or zero import duties in partner countries',
    items: [
      {
        name: 'EUR.1 Movement Certificate',
        filename: 'eur1-certificate.html',
        tag: 'EU / FTA',
        tagColor: 'bg-yellow-100 text-yellow-800',
        icon: 'FileSignature',
        desc: 'EUR.1 for preferential duty under EU-India agreements',
        countries: 'EU member states',
      },
      {
        name: 'SAFTA Certificate of Origin',
        filename: 'safta-coo.html',
        tag: 'SAARC',
        tagColor: 'bg-teal-100 text-teal-800',
        icon: 'FileBadge',
        desc: 'SAFTA COO for preferential duty in SAARC countries',
        countries: 'SAARC countries',
      },
      {
        name: 'Arab League COO (AACO Form)',
        filename: 'arab-league-coo.html',
        tag: 'Arab League / GCC',
        tagColor: 'bg-amber-100 text-amber-800',
        icon: 'FileSpreadsheet',
        desc: 'Arab League COO for duty benefits in Arab League states',
        countries: 'Arab League / GCC countries',
      },
    ],
  },
  {
    title: 'Financial, Incentive & India Compliance Documents',
    description:
      'For payment security, GST, forex, and claiming all export benefits',
    items: [
      {
        name: 'LC Compliance Checklist',
        filename: 'lc-compliance-checklist.html',
        tag: 'Universal',
        tagColor: 'bg-blue-100 text-blue-800',
        icon: 'CheckSquare',
        desc: 'Letter of Credit compliance checklist for LC payments',
        countries: 'All countries (LC payments)',
      },
      {
        name: 'Bill of Exchange / Trade Draft',
        filename: 'bill-of-exchange.html',
        tag: 'Universal',
        tagColor: 'bg-blue-100 text-blue-800',
        icon: 'Receipt',
        desc: 'Bill of Exchange for documentary collection payments',
        countries: 'All countries',
      },
      {
        name: 'GST LUT Application',
        filename: 'gst-lut-application.html',
        tag: 'GST / FEMA',
        tagColor: 'bg-purple-100 text-purple-800',
        icon: 'FileStack',
        desc: 'GST Letter of Undertaking (LUT) for zero-rated exports',
        countries: 'India compliance',
      },
      {
        name: 'RoDTEP / Drawback Claim',
        filename: 'rodtep-drawback-claim.html',
        tag: 'Incentives',
        tagColor: 'bg-pink-100 text-pink-800',
        icon: 'DollarSign',
        desc: 'RoDTEP and duty drawback claim form for export incentives',
        countries: 'India compliance',
      },
      {
        name: 'BRC / FIRC Declaration',
        filename: 'brc-firc-declaration.html',
        tag: 'GST / FEMA',
        tagColor: 'bg-purple-100 text-purple-800',
        icon: 'FileCheck',
        desc: 'Bank Realisation Certificate / FIRC declaration for forex',
        countries: 'India compliance',
      },
      {
        name: 'Shipping Bill Checklist',
        filename: 'shipping-bill-checklist.html',
        tag: 'Universal',
        tagColor: 'bg-blue-100 text-blue-800',
        icon: 'ClipboardList',
        desc: 'Shipping bill preparation checklist for customs clearance',
        countries: 'All countries',
      },
      {
        name: 'Export Readiness Checklist',
        filename: 'export-readiness-checklist.html',
        tag: 'Universal',
        tagColor: 'bg-blue-100 text-blue-800',
        icon: 'ListChecks',
        desc: 'Complete export readiness checklist for new exporters',
        countries: 'All countries',
      },
    ],
  },
]
