import type { Portal, PortalCategory, PortalColor } from '@/types'

export const portalCategories: PortalCategory[] = [
  'All',
  'Market Research',
  'Compliance',
  'Analytics',
  'Food & Agri',
  'Customs',
  'Investment',
  'Transport & Logistics',
]

export const categoryFilterStyles: Record<
  PortalCategory,
  { active: string; idle: string }
> = {
  All: {
    active: 'bg-foreground text-white border-foreground',
    idle: 'bg-background text-foreground border-border hover:bg-muted',
  },
  'Market Research': {
    active: 'bg-blue-600 text-white border-blue-600',
    idle: 'bg-background text-blue-600 border-blue-200 hover:bg-blue-50',
  },
  Compliance: {
    active: 'bg-indigo-600 text-white border-indigo-600',
    idle: 'bg-background text-indigo-600 border-indigo-200 hover:bg-indigo-50',
  },
  Analytics: {
    active: 'bg-teal-600 text-white border-teal-600',
    idle: 'bg-background text-teal-600 border-teal-200 hover:bg-teal-50',
  },
  'Food & Agri': {
    active: 'bg-emerald-600 text-white border-emerald-600',
    idle: 'bg-background text-emerald-600 border-emerald-200 hover:bg-emerald-50',
  },
  Customs: {
    active: 'bg-amber-600 text-white border-amber-600',
    idle: 'bg-background text-amber-600 border-amber-200 hover:bg-amber-50',
  },
  Investment: {
    active: 'bg-purple-600 text-white border-purple-600',
    idle: 'bg-background text-purple-600 border-purple-200 hover:bg-purple-50',
  },
  'Transport & Logistics': {
    active: 'bg-cyan-600 text-white border-cyan-600',
    idle: 'bg-background text-cyan-600 border-cyan-200 hover:bg-cyan-50',
  },
}

export const portalGradients: Record<PortalColor, string> = {
  blue: 'from-blue-500 to-blue-600',
  indigo: 'from-indigo-500 to-indigo-600',
  orange: 'from-orange-500 to-orange-600',
  teal: 'from-teal-500 to-teal-600',
  emerald: 'from-emerald-500 to-emerald-600',
  purple: 'from-purple-500 to-purple-600',
  pink: 'from-pink-500 to-pink-600',
  green: 'from-green-500 to-green-600',
  red: 'from-red-500 to-red-600',
  amber: 'from-amber-500 to-amber-600',
  cyan: 'from-cyan-500 to-cyan-600',
}

export const portalTextColors: Record<PortalColor, string> = {
  blue: 'text-blue-600',
  indigo: 'text-indigo-600',
  orange: 'text-orange-600',
  teal: 'text-teal-600',
  emerald: 'text-emerald-600',
  purple: 'text-purple-600',
  pink: 'text-pink-600',
  green: 'text-green-600',
  red: 'text-red-600',
  amber: 'text-amber-600',
  cyan: 'text-cyan-600',
}

export const stageBadgeColors: Record<string, string> = {
  'Pre-Export': 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400',
  Registration: 'bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-400',
  'Product Selection': 'bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-400',
  'Market Selection': 'bg-teal-100 text-teal-800 dark:bg-teal-900/30 dark:text-teal-400',
  Research: 'bg-cyan-100 text-cyan-800 dark:bg-cyan-900/30 dark:text-cyan-400',
  Execution: 'bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-400',
  Certification: 'bg-success/20 text-success',
  Shipping: 'bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-400',
  Setup: 'bg-pink-100 text-pink-800 dark:bg-pink-900/30 dark:text-pink-400',
}

export const costBadgeColors: Record<string, string> = {
  Free: 'bg-success/20 text-success',
  'Paid (IEC Rs.500)': 'bg-warning/20 text-warning',
  'Paid (Membership)': 'bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-400',
  'Paid (Registration)': 'bg-destructive/20 text-destructive',
}

export const portals: Portal[] = [
  {
    id: 'dgft',
    name: 'DGFT',
    url: 'https://dgft.gov.in',
    description:
      'Directorate General of Foreign Trade — Your gateway for import-export code (IEC), export policy, and FTP guidance.',
    category: 'Compliance',
    bestFor: 'IEC Registration, FTP Guidelines, Export Policy',
    whyImportant:
      'DGFT is the primary government body managing India\'s foreign trade policy. It issues IEC (mandatory for all exporters), publishes FTP (Foreign Trade Policy) updates, and administers various export promotion schemes.',
    whoShouldUse: 'Every Indian exporter, freight forwarder, and trade consultant.',
    keyFeatures: [
      'Online IEC Application & Modification',
      'FTP (Foreign Trade Policy) 2023-28',
      'Export Obligation (EO) Management',
      'RoSCTL & other scheme applications',
      'Grievance & Helpdesk Support',
    ],
    benefits: 'Get your Importer Exporter Code (IEC) in 2–3 working days online. Access all FTP circulars and notifications in real time.',
    registration: 'Apply online at dgft.gov.in',
    authority: 'Ministry of Commerce & Industry, Govt. of India',
    exportStage: 'Registration',
    cost: 'Paid (IEC Rs.500)',
    mobileFriendly: true,
    icon: 'FileText',
    color: 'blue',
    phone: '1800-111-550',
    email: 'helpdesk@dgft.gov.in',
    helpdesk: 'DGFT Helpdesk: 1800-111-550',
    headTitle: 'DGFT Headquarters',
    headOfficePhone: '011-23061562',
    whatsapp: '',
  },
  {
    id: 'icegate',
    name: 'ICEGATE',
    url: 'https://icegate.gov.in',
    description:
      'Indian Customs EDI Gateway — Electronic Data Interchange for customs clearance, shipping bills, and import manifest.',
    category: 'Customs',
    bestFor: 'Customs Clearance, Shipping Bills, EDI Filing',
    whyImportant:
      'ICEGATE is the customs EDI (Electronic Data Interchange) gateway. All export-import shipments must file shipping bills or bills of entry through ICEGATE for customs clearance.',
    whoShouldUse: 'Exporters, importers, customs brokers, CHAs, logistics companies.',
    keyFeatures: [
      'e-Sanchika (Electronic Baggage)',
      'Tourist Baggage & Duty-Free Clearance',
      'Customs Duty Payment',
      'Shipping Bill (SB) & Bill of Entry (BE) Filing',
      'Track container & cargo status',
    ],
    benefits: 'Seamless 24x7 electronic customs clearance without physical paperwork.',
    registration: 'Registration via ICEGATE portal (free)',
    authority: 'CBIC (Central Board of Indirect Taxes & Customs), Govt. of India',
    exportStage: 'Shipping',
    cost: 'Free',
    mobileFriendly: true,
    icon: 'Ship',
    color: 'indigo',
    phone: '1800-3010-1000',
    email: 'helpdesk@icegate.gov.in',
    helpdesk: 'ICEGATE Helpdesk (24x7): 1800-3010-1000',
    headTitle: 'CBIC / ICEGATE',
    headOfficePhone: '1800-3010-1000',
    whatsapp: '',
  },
  {
    id: 'indian-trade-portal',
    name: 'Indian Trade Portal',
    url: 'https://indiantradeportal.in',
    description:
      'Comprehensive trade information portal — HS codes, tariffs, ITC(HS) classification, and market access data.',
    category: 'Market Research',
    bestFor: 'HS Code Search, Tariff Rates, ITC(HS) Classification',
    whyImportant:
      'The Indian Trade Portal provides the complete ITC(HS) classification system, tariff rates, export-import policy, and market access information for Indian exporters and importers.',
    whoShouldUse: 'Exporters, importers, trade analysts, customs brokers.',
    keyFeatures: [
      'ITC(HS) Code Search (8-digit)',
      'Customs Tariff & Duty Calculator',
      'Export-Import Policy (ITC(HS) 2023)',
      'Notification & Circular Library',
      'Trade Statistics & Market Access',
    ],
    benefits: 'Find correct HS codes and tariff rates instantly. Ensure compliance with ITC(HS) classifications.',
    registration: 'No registration required (open access)',
    authority: 'DGFT, Ministry of Commerce & Industry',
    exportStage: 'Research',
    cost: 'Free',
    mobileFriendly: true,
    icon: 'Search',
    color: 'orange',
    phone: '1800-111-550',
    email: 'helpdesk@dgft.gov.in',
    helpdesk: 'DGFT Helpdesk: 1800-111-550',
    headTitle: 'DGFT',
    headOfficePhone: '011-23061562',
    whatsapp: '',
  },
  {
    id: 'niryat',
    name: 'NIRYAT',
    url: 'https://niryat.gov.in',
    description:
      'National Import-Export Record for Yearly Analysis of Trade — India\'s advanced trade analytics and data visualization platform.',
    category: 'Analytics',
    bestFor: 'Trade Analytics, Export-Import Data, Market Intelligence',
    whyImportant:
      'NIRYAT is the government\'s flagship trade analytics portal. It provides detailed export-import data, market intelligence, and trend analysis tools for policymakers and exporters.',
    whoShouldUse: 'Exporters, trade analysts, researchers, policymakers.',
    keyFeatures: [
      'Commodity-wise export-import data',
      'Country-wise trade analysis',
      'Interactive dashboards & reports',
      'District-level export data',
      'Yearly/monthly trade trends',
    ],
    benefits: 'Make data-driven export decisions with real-time trade analytics and market intelligence.',
    registration: 'Free registration on portal',
    authority: 'Ministry of Commerce & Industry, Govt. of India',
    exportStage: 'Research',
    cost: 'Free',
    mobileFriendly: true,
    icon: 'BarChart3',
    color: 'teal',
    phone: '',
    email: '',
    helpdesk: 'NIRYAT portal support (via website)',
    headTitle: 'Ministry of Commerce',
    headOfficePhone: '',
    whatsapp: '',
  },
  {
    id: 'apeda',
    name: 'APEDA',
    url: 'https://apeda.gov.in',
    description:
      'Agricultural and Processed Food Products Export Development Authority — Promoting agri-exports from India.',
    category: 'Food & Agri',
    bestFor: 'Agri-Export Certification, RCMC, Market Access for Food Products',
    whyImportant:
      'APEDA is the nodal agency for agricultural and processed food exports. It issues RCMC (Registration-cum-Membership Certificate), provides market access support, and organizes trade delegations for agri-exporters.',
    whoShouldUse: 'Exporters of agricultural products, processed foods, meat, dairy, poultry, and marine products.',
    keyFeatures: [
      'RCMC Application & Renewal',
      'Market Access Initiative (MAI)',
      'Export Inspection & Certification',
      'Organic Certification Support',
      'Trade Fair & Buyer-Seller Meet Participation',
    ],
    benefits: 'Get RCMC certification, access international trade fairs, and avail MAI subsidies for agri-exports.',
    registration: 'Online registration at apeda.gov.in',
    authority: 'Ministry of Commerce & Industry, Govt. of India',
    exportStage: 'Certification',
    cost: 'Free',
    mobileFriendly: true,
    icon: 'Sprout',
    color: 'emerald',
    phone: '1800-111-175',
    email: 'helpdesk@apeda.gov.in',
    helpdesk: 'APEDA Helpline: 1800-111-175',
    headTitle: 'APEDA Headquarters',
    headOfficePhone: '011-26516520',
    whatsapp: '',
  },
  {
    id: 'fieo',
    name: 'FIEO',
    url: 'https://fieo.org',
    description:
      'Federation of Indian Export Organisations — India\'s apex export promotion body for IEAs, buyer-seller meets, and trade delegations.',
    category: 'Market Research',
    bestFor: 'Export Promotion, Buyer-Seller Meets, Trade Delegations',
    whyImportant:
      'FIEO is the apex body of Indian export promotion councils and organizations. It organizes buyer-seller meets, trade delegations, and provides market access support to Indian exporters.',
    whoShouldUse: 'Exporters seeking international buyers, trade delegations, and export promotion support.',
    keyFeatures: [
      'Buyer-Seller Meets (BSMs)',
      'International Trade Delegations',
      'Market Access & Research Reports',
      'Export Facilitation & Guidance',
      'Trade Grievance Redressal',
    ],
    benefits: 'Connect with international buyers through FIEO\'s global network of buyer-seller meets and trade delegations.',
    registration: 'Membership-based (fee applies)',
    authority: 'Ministry of Commerce & Industry, Govt. of India',
    exportStage: 'Pre-Export',
    cost: 'Paid (Membership)',
    mobileFriendly: true,
    icon: 'Globe',
    color: 'purple',
    phone: '011-26153040',
    email: 'fieo@fieo.org',
    helpdesk: 'FIEO Delhi: 011-26153040',
    headTitle: 'FIEO Headquarters',
    headOfficePhone: '011-26153040',
    whatsapp: '',
  },
  {
    id: 'epces',
    name: 'EPCES',
    url: 'https://www.epces.in/',
    description:
      'Export Promotion Council for EOUs & SEZs — RCMC registration, trade facilitation, and policy advocacy for export-oriented units and special economic zones.',
    category: 'Market Research',
    bestFor: 'EOU/SEZ RCMC, Export Promotion, Policy Advocacy',
    whyImportant:
      'EPCES (Export Promotion Council for EOUs & SEZs) supports export-oriented units and SEZ developers with RCMC issuance, trade facilitation, market intelligence, and policy advocacy to enhance export competitiveness.',
    whoShouldUse: 'EOU and SEZ units, developers, and exporters seeking RCMC certification and export promotion support.',
    keyFeatures: [
      'RCMC Registration & Renewal',
      'Certificate of Origin (Non-Preferential)',
      'Trade delegations & exhibitions',
      'Market research & intelligence',
      'Policy advocacy & grievance handling',
    ],
    benefits: 'Obtain EOU/SEZ RCMC certification and access targeted export promotion programs, trade data, and policy support.',
    registration: 'Membership-based (varies by unit category)',
    authority: 'Ministry of Commerce & Industry, Govt. of India',
    exportStage: 'Setup',
    cost: 'Paid (Membership)',
    mobileFriendly: false,
    icon: 'Building2',
    color: 'pink',
    phone: '+91-11-23329766-69',
    email: 'query@epces.in',
    helpdesk: 'EPCES Helpline: +91-11-23329766-69',
    headTitle: 'EPCES — EOUs & SEZs',
    headOfficePhone: '+91-11-23329766-69',
    whatsapp: '',
  },
  {
    id: 'odop',
    name: 'ODOP',
    url: 'https://odop.mofpi.gov.in/odop/',
    description:
      'One District One Product — Identify and promote unique products from each district for export and branding.',
    category: 'Market Research',
    bestFor: 'District-Level Product Identification, Branding, Local Sourcing',
    whyImportant:
      'ODOP (One District One Product) is a government initiative to identify and promote unique products from each district. It helps exporters discover new product categories and source authentic local products.',
    whoShouldUse: 'Exporters looking for unique local products, MSMEs, and district-level trade development.',
    keyFeatures: [
      'District-wise product listing',
      'Product profiling & branding support',
      'Export promotion for local products',
      'GI tag & geographical indication support',
      'MSME & artisan connect',
    ],
    benefits: 'Discover unique products from every district and build an export brand around India\'s diverse local specialties.',
    registration: 'Through district industry centers',
    authority: 'Ministry of Commerce & Industry, Govt. of India',
    exportStage: 'Product Selection',
    cost: 'Free',
    mobileFriendly: true,
    icon: 'MapPin',
    color: 'green',
    phone: '',
    email: '',
    helpdesk: 'Contact district industry center',
    headTitle: 'ODOP Portal',
    headOfficePhone: '',
    whatsapp: '',
  },
  {
    id: 'tradestat',
    name: 'TradeStat',
    url: 'https://tradestat.commerce.gov.in/eidb/commodity_wise_export',
    description:
      'Commodity-wise trade data, export-import statistics, and market analysis dashboard for informed decision-making.',
    category: 'Analytics',
    bestFor: 'Commodity Trade Data, Import-Export Trends, Market Analysis',
    whyImportant:
      'TradeStat provides comprehensive export-import data across commodities, countries, and time periods. It helps exporters identify market trends, demand patterns, and competitive analysis.',
    whoShouldUse: 'Exporters, trade analysts, researchers, and businesses planning market entry.',
    keyFeatures: [
      'Commodity-wise trade statistics',
      'Country-wise export-import data',
      'Year-over-year trend analysis',
      'Competitive market analysis',
      'Data export & reporting tools',
    ],
    benefits: 'Analyze trade patterns, identify high-demand markets, and make informed export decisions with accurate data.',
    registration: 'Free access on portal',
    authority: 'Ministry of Commerce & Industry, Govt. of India',
    exportStage: 'Market Selection',
    cost: 'Free',
    mobileFriendly: true,
    icon: 'PieChart',
    color: 'red',
    phone: '',
    email: '',
    helpdesk: 'Portal support available online',
    headTitle: 'TradeStat Portal',
    headOfficePhone: '',
    whatsapp: '',
  },
  {
    id: 'invest-india',
    name: 'Invest India',
    url: 'https://investindia.gov.in',
    description:
      'National Investment Promotion & Facilitation Agency — Guiding investment, startup support, and export incentives.',
    category: 'Investment',
    bestFor: 'Investment Guidance, Startup Support, Incentive Information',
    whyImportant:
      'Invest India is the national investment promotion agency. It provides guidance on FDI, startup ecosystem, and various government incentives for businesses including exporters.',
    whoShouldUse: 'Startups, investors, exporters looking for investment opportunities and incentive schemes.',
    keyFeatures: [
      'Investment promotion & facilitation',
      'Startup India support & registration',
      'State-level incentive information',
      'Sector-specific investment guides',
      'Export incentive scheme assistance',
    ],
    benefits: 'Get expert guidance on investment opportunities, startup registration, and government incentive schemes for exporters.',
    registration: 'Online inquiry & registration',
    authority: 'Ministry of Commerce & Industry, Govt. of India',
    exportStage: 'Setup',
    cost: 'Free',
    mobileFriendly: true,
    icon: 'TrendingUp',
    color: 'amber',
    phone: '011-23048155',
    email: 'invest@investindia.org.in',
    helpdesk: 'Invest India: 011-23048155',
    headTitle: 'Invest India',
    headOfficePhone: '011-23048155',
    whatsapp: '',
  },
  {
    id: 'artworkflow-compliance',
    name: 'ArtworkFlow HQ',
    url: 'https://www.artworkflowhq.com/artwork-compliance',
    description:
      'National body for packaging standards and quality certification — ISPM-15 compliance, wooden packaging inspection, and packaging waste management.',
    category: 'Transport & Logistics',
    bestFor: 'Packaging Compliance, ISPM-15 Certification, Quality Assurance',
    whyImportant:
      'ArtworkFlow HQ ensures all export packaging meets national and international standards. It administers ISPM-15 fumigation certificate requirements, wooden packaging inspection protocols, and export packaging waste compliance for smooth customs clearance.',
    whoShouldUse: 'Exporters using wooden packaging, shipping companies, manufacturing units, and quality assurance professionals.',
    keyFeatures: [
      'ISPM-15 Fumigation Certificate Issuance',
      'Wood Packaging Inspection & Certification',
      'Packaging Waste Management Advisory',
      'Export Packaging Compliance Testing',
      'Fumigation Protocol Certification',
    ],
    benefits: 'Ensure your export packaging meets all international standards and customs requirements. Avoid shipment delays and rejections with certified packaging compliance.',
    registration: 'Apply online with packaging documentation and inspection results',
    authority: 'Ministry of Commerce & Industry, Govt. of India',
    exportStage: 'Setup',
    cost: 'Free (After initial inspection$500)',
    mobileFriendly: true,
    icon: 'Package',
    color: 'cyan',
    phone: '1800-123-456',
    email: 'contact@artworkflowhq.com',
    helpdesk: 'ArtworkFlow HQ Helpline: 1800-123-456',
    headTitle: 'ArtworkFlow HQ',
    headOfficePhone: '011-41501234',
    whatsapp: '',
  },
  {
    id: 'gjepc',
    name: 'Gem and Jewellery Export Promotion Council (GJEPC)',
    url: 'https://gjepc.org/',
    description:
      'Promotion of gems and jewellery exports; organizes international trade shows, provides market intelligence and policy support.',
    category: 'Export Promotion',
    bestFor: 'Gems & Jewellery',
    whyImportant:
      'GJEPC promotes the export of gems and jewellery through international trade shows, buyer-seller meets, and market intelligence. It provides policy advocacy, quality certification support, and industry networking for exporters.',
    whoShouldUse: 'Gem and jewellery exporters, manufacturers, traders, and artisans seeking export promotion and market access.',
    keyFeatures: [
      'International trade shows & exhibitions',
      'Buyer-seller meets & B2B networking',
      'Market intelligence & trend reports',
      'Export policy advocacy',
      'Quality certification guidance',
    ],
    benefits: 'Access global buyers, showcase products at international trade fairs, and stay ahead with market intelligence and policy support.',
    registration: 'Membership-based',
    authority: 'Ministry of Commerce & Industry, Govt. of India',
    exportStage: 'EPC',
    cost: 'Paid',
    mobileFriendly: true,
    icon: 'Gem',
    color: 'amber',
    phone: '+91-22-26544600',
    email: 'info@gjepcindia.com',
    helpdesk: 'GJEPC Helpline: +91-22-26544600',
    headTitle: 'GJEPC — Gem & Jewellery EPC',
    headOfficePhone: '+91-22-26544600',
    whatsapp: '',
  },
  {
    id: 'ecgc',
    name: 'ECGC',
    url: 'https://ecgc.in/',
    description:
      'Export Credit Guarantee Corporation of India — Export credit insurance, buyer credit reports, and guarantees against payment default for Indian exporters.',
    category: 'Market Research',
    bestFor: 'Export Credit Insurance, Buyer Credit Report, Risk Cover',
    whyImportant:
      'ECGC provides export credit insurance to protect Indian exporters against commercial and political risks of non-payment. It also offers buyer credit reports to assess the creditworthiness of overseas buyers before shipping.',
    whoShouldUse: 'Every Indian exporter wanting to insure receivables, check buyer credibility, and secure export finance.',
    keyFeatures: [
      'Standard & Specific Buyer Policies',
      'Buyer Credit Limit (BCL) Assessment',
      'Buyer Credit Reports & Ratings',
      'Packing Credit Guarantee for Banks',
      'Export Credit Insurance for Banks',
    ],
    benefits: 'Protect 80–90% of invoice value against buyer default. Assess buyer creditworthiness before shipping. Secure better export financing from banks.',
    registration: 'Online registration at ecgc.in',
    authority: 'Ministry of Commerce & Industry, Govt. of India',
    exportStage: 'Pre-Export',
    cost: 'Paid (Premium 0.3–0.8% of turnover)',
    mobileFriendly: true,
    icon: 'Shield',
    color: 'blue',
    phone: '022-66138421',
    email: 'projectexport@ecgc.in',
    helpdesk: 'ECGC Helpline: 022-66138421',
    headTitle: 'ECGC Limited',
    headOfficePhone: '022-66138421',
    whatsapp: '',
  },
  {
    id: 'buyer-credibility-check',
    name: 'Buyer Credibility Check',
    url: 'https://www.credlix.com/export-factoring/buyer-credit-check',
    description:
      'Check international buyer creditworthiness instantly — get detailed credit reports, payment history, and risk assessment before shipping.',
    category: 'Analytics',
    bestFor: 'Buyer Credit Check, Risk Assessment, Due Diligence',
    whyImportant:
      'Verify your overseas buyer\'s financial credibility before accepting orders. Avoid payment defaults, late payments, and fraud by running a quick credit check on any international buyer.',
    whoShouldUse: 'Exporters wanting to verify buyer credibility before shipping on credit terms (DA/DP/open account).',
    keyFeatures: [
      'Instant buyer credit report',
      'Global credit database scan',
      'Payment history & risk score',
      'Buyer financial health analysis',
      'Recommended credit limit',
    ],
    benefits: 'Make informed decisions before extending credit to new buyers. Reduce risk of non-payment and protect your cash flow.',
    registration: 'Free instant check (report-based pricing)',
    authority: 'Private',
    exportStage: 'Pre-Export',
    cost: 'Free (Basic) / Paid (Detailed Report)',
    mobileFriendly: true,
    icon: 'SearchCheck',
    color: 'teal',
    phone: '',
    email: '',
    helpdesk: 'Online support via website',
    headTitle: 'Buyer Credit Check',
    headOfficePhone: '',
    whatsapp: '',
  },
  {
    id: 'new-india-assurance',
    name: 'New India Assurance',
    url: 'https://www.newindia.co.in/portal/insurer/marine-insurance',
    description:
      'Marine cargo insurance, export credit insurance, and transit risk coverage for Indian exporters — PSU insurer with global network.',
    category: 'Compliance',
    bestFor: 'Marine Cargo Insurance, Transit Risk, Export Coverage',
    whyImportant:
      'New India Assurance is India\'s largest public sector general insurer offering comprehensive marine insurance policies covering cargo loss, damage, and transit risks for export shipments worldwide.',
    whoShouldUse: 'Exporters needing marine cargo insurance, transit risk cover, and comprehensive export shipment protection.',
    keyFeatures: [
      'Marine Cargo Insurance (Institute Clauses)',
      'Export Credit Insurance cover',
      'Warehouse-to-warehouse coverage',
      'Global claim settlement network',
      'Open policy & specific policy options',
    ],
    benefits: 'Protect your export cargo against loss, damage, theft, and transit risks with India\'s largest PSU insurer.',
    registration: 'Online or through branch network',
    authority: 'Govt. of India (PSU)',
    exportStage: 'Shipping',
    cost: 'Paid (Premium based on cargo value)',
    mobileFriendly: true,
    icon: 'Shield',
    color: 'red',
    phone: '1800-209-0910',
    email: 'customersupport@newindia.co.in',
    helpdesk: 'New India Assurance Helpline: 1800-209-0910',
    headTitle: 'New India Assurance',
    headOfficePhone: '022-22682500',
    whatsapp: '',
  },
  {
    id: 'icici-lombard-marine',
    name: 'ICICI Lombard',
    url: 'https://www.icicilombard.com/marine-insurance',
    description:
      'Marine insurance for export-import cargo — comprehensive coverage for goods in transit by sea, air, and road.',
    category: 'Compliance',
    bestFor: 'Marine Cargo Insurance, Transit Insurance, Export Cover',
    whyImportant:
      'ICICI Lombard offers comprehensive marine insurance policies for exporters covering cargo loss, damage, delay, and theft during international transit by sea, air, or land.',
    whoShouldUse: 'Exporters and importers seeking marine cargo insurance with easy online purchase and quick claim settlement.',
    keyFeatures: [
      'Marine Cargo Insurance',
      'Inland Transit (Rail/Road) coverage',
      'Air Cargo insurance',
      'Open policy for regular exporters',
      'Online policy issuance & claims',
    ],
    benefits: 'Get instant marine cargo insurance online with comprehensive coverage for your export shipments.',
    registration: 'Online purchase at icicilombard.com',
    authority: 'Private',
    exportStage: 'Shipping',
    cost: 'Paid (Premium based on cargo value)',
    mobileFriendly: true,
    icon: 'Shield',
    color: 'red',
    phone: '1800-2666',
    email: 'customersupport@icicilombard.com',
    helpdesk: 'ICICI Lombard Helpline: 1800-2666',
    headTitle: 'ICICI Lombard Marine Insurance',
    headOfficePhone: '022-61967777',
    whatsapp: '',
  },
  {
    id: 'tata-aig-marine',
    name: 'Tata AIG General Insurance',
    url: 'https://www.tataaig.com/marine-insurance',
    description:
      'Marine and transit insurance for exporters — cargo cover, hull insurance, and liability protection for international trade.',
    category: 'Compliance',
    bestFor: 'Marine Cargo, Transit Insurance, Export Risk Cover',
    whyImportant:
      'Tata AIG provides comprehensive marine insurance solutions for exporters including cargo insurance, transit risk coverage, and supply chain protection with global claim support.',
    whoShouldUse: 'Exporters requiring marine cargo insurance, transit risk management, and supply chain protection.',
    keyFeatures: [
      'Marine Cargo Insurance (Sea/Air/Road)',
      'Stock throughput policy',
      'Warehouse-to-warehouse cover',
      'Global claim network',
      'Open & specific policies',
    ],
    benefits: 'Comprehensive cargo protection from factory to destination with Tata AIG\'s trusted marine insurance.',
    registration: 'Online or through agent',
    authority: 'Private',
    exportStage: 'Shipping',
    cost: 'Paid (Premium based on cargo value)',
    mobileFriendly: true,
    icon: 'Shield',
    color: 'red',
    phone: '1800-266-7788',
    email: 'customersupport@tataaig.com',
    helpdesk: 'Tata AIG Helpline: 1800-266-7788',
    headTitle: 'Tata AIG Marine Insurance',
    headOfficePhone: '022-66938100',
    whatsapp: '',
  },
]
